// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "title": "Welcome to our website!",
    "description": "This is the English version."
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, km {ខ្មែរ} en {English} other {Unknown}}"
  },
  "CommonValidate": {
    "require": "Required",
    "minText2": "must be at least 2 characters"
  },
  "CommonField": {
    "fullName": "Full name",
    "gender": "{gender, select, F {Female} M {Male} other {Unknown}}",
    "dateOfBirth": "Date Of Birth",
    "occupation": "occupation",
    "fatherName": "Father Name",
    "montherName": "Mother Name",
    "placeOfBirth": "Place Of Birth",
    "address": "Address"
  },
  "common": {
    "yes": "Yes",
    "no": "No",
    "cancel": "Cancel",
    "delete": "Delete",
    "save": "Save",
    "edit": "Edit",
    "done": "Done",
    "titleDeleteConfirm": "Confirm Deletion"
  },
  "student": {
    "title": "Students",
    "name": "Name",
    "email": "Email",
    "deleteConfirmation": "Are you sure you want to delete this student?",
    "deleteMultiple": "Are you sure you want to delete {count} students?",
    "deleteSuccess": "Student deleted successfully",
    "btn": {
      "multiAdd": "Add Multi Students",
      "singleAdd": "Add a Student",
      "deleteStu": "Delete Student"
    },
    "DialogInsert": {
      "title": "Please enter student information"
    }
  }
};
export default messages;