// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "title": "Welcome to our website!",
    "description": "This is the English version."
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, km {ភាសាខ្មែរ} en {English} other {Unknown}}"
  },
  "CommonValidate": {
    "require": "Required",
    "minText2": "must be at least 2 characters",
    "cannotEmpty": "Can not empty"
  },
  "CommonField": {
    "id": "ID",
    "fullName": "Full name",
    "firstName": "First name",
    "lastName": "last name",
    "sex": "Gender",
    "gender": "{gender, select, F {Female} M {Male} other {Unknown}}",
    "dateOfBirth": "Date Of Birth",
    "occupation": "Occupation",
    "fatherName": "Father Name",
    "montherName": "Mother Name",
    "placeOfBirth": "Place Of Birth",
    "address": "Address",
    "subject": "Subject",
    "code": "Code"
  },
  "Common": {
    "yes": "Yes",
    "no": "No",
    "cancel": "Cancel",
    "back": "Back",
    "delete": "Delete",
    "save": "Save",
    "edit": "Edit",
    "done": "Done",
    "search": "Search",
    "download": "Download",
    "downloadExcel": "Download Excel",
    "print": "Print",
    "titleDeleteConfirm": "Confirm Deletion",
    "male": "Male",
    "female": "Female",
    "total": "Total",
    "people": "People",
    "studyYear": "Year",
    "grade": "Grade",
    "classroom": "Classroom",
    "createClassroom": "Create new Classroom",
    "monthly": "Monthly",
    "semester": "Semester",
    "months": {
      "january": "January",
      "february": "February",
      "march": "March",
      "april": "April",
      "may": "May",
      "june": "June",
      "july": "July",
      "august": "August",
      "september": "September",
      "october": "October",
      "november": "November",
      "december": "December"
    }
  },
  "Student": {
    "title": "Students",
    "name": "Name",
    "email": "Email",
    "deleteConfirmation": "Are you sure you want to delete this student?",
    "deleteMultiple": "Are you sure you want to delete {count} students?",
    "deleteSuccess": "Student deleted successfully",
    "btn": {
      "multiAdd": "Adds",
      "singleAdd": "Add",
      "deleteStu": "Delete"
    },
    "DialogInsert": {
      "title": "Please enter student information"
    }
  },
  "MonthlyExam": {
    "viewRanking": "Montly ranking",
    "viewAll": "View all",
    "monthlyScores": "Monthly scores",
    "enterAverage": "Enter average"
  },
  "SemesterExam": {
    "viewRanking": "Semester ranking",
    "semesterScores": "Semester scores",
    "semesterlyAverageRanking": "Semesterly average"
  },
  "MenuList": {
    "home": "Home",
    "classroom": "Classroom",
    "student": "Student",
    "monthlyExam": "Monthly Exam",
    "SemesterExam": "Semester Exam",
    "setting": "Setting",
    "about": "About",
    "feedback": "Feedback",
    "manageSubject": "Manage Subject"
  }
};
export default messages;