// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "title": "Welcome to our website!",
    "description": "This is the English version."
  },
  "Dashboard": {
    "title": "Dashboard",
    "welcome": "Welcome back, {name}!",
    "totalStudents": "Total Students",
    "totalSubjects": "Total Subjects",
    "totalExams": "Total Exams",
    "avgClassScore": "Avg Class Score"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, km {ភាសាខ្មែរ} en {English} other {Unknown}}"
  },
  "CommonValidate": {
    "require": "Required",
    "minText2": "must be at least 2 characters",
    "cannotEmpty": "Can not empty",
    "noChange": "Nothing Changed",
    "inputFirst": "Please input {fullName} first!"
  },
  "CommonField": {
    "id": "No",
    "idCard": "ID",
    "fullName": "Full name",
    "firstName": "First name",
    "teacherName": "Teacher name",
    "credit": "Credit",
    "description": "Description",
    "maxScore": "Max Scores",
    "lastName": "last name",
    "sex": "Gender",
    "gender": "{gender, select, F {Female} M {Male} other {Unknown}}",
    "dateOfBirth": "Date Of Birth",
    "occupation": "Occupation",
    "fatherName": "Father Name",
    "montherName": "Mother Name",
    "placeOfBirth": "Place Of Birth",
    "address": "Address",
    "subject": "Subject",
    "code": "Code",
    "ranking": "Ranking",
    "totalScore": "Total Score",
    "average": "Average",
    "grade": "Grade"
  },
  "Common": {
    "yes": "Yes",
    "no": "No",
    "add": "Add",
    "create": "Create",
    "update": "Update",
    "cancel": "Cancel",
    "back": "Back",
    "delete": "Delete",
    "save": "Save",
    "edit": "Edit",
    "done": "Done",
    "search": "Search",
    "manage": "Manage",
    "download": "Download",
    "downloadExcel": "Download Excel",
    "print": "Print",
    "import": "Import Excel",
    "titleDeleteConfirm": "Confirm Deletion",
    "deleteConfirmation": "Are you sure you want to delete this {subject}?",
    "male": "Male",
    "female": "Female",
    "total": "Total",
    "people": "People",
    "student": "Students",
    "subject": "Subjects",
    "attendance": "Attendance",
    "exam": "Exam",
    "studyYear": "Year",
    "grade": "Grade",
    "classroom": "Classroom",
    "createClassroom": "Create new Classroom",
    "monthly": "Monthly",
    "semester": "Semester",
    "mekun": "Credit",
    "months": {
      "Jan": "January",
      "Feb": "February",
      "Mar": "March",
      "Apr": "April",
      "May": "May",
      "Jun": "June",
      "Jul": "July",
      "Aug": "August",
      "Sep": "September",
      "Oct": "October",
      "Nov": "November",
      "Dec": "December"
    },
    "errorOccurred": "An error occurred. Please try again."
  },
  "Classroom": {
    "createNew": "Create new class",
    "gradeName": "Grade level",
    "className": "Class name",
    "yearOfStudying": "Academic Year",
    "startYear": "Start Year",
    "endYear": "End Year",
    "totalStu": "Total Students",
    "totalFemaleStu": "Total Female Students",
    "totalMaleStu": "Total Male Students",
    "totalSub": "Total Subjects",
    "DialogInsert": {
      "title": "Please enter Class information"
    }
  },
  "Student": {
    "title": "Students",
    "name": "Name",
    "email": "Email",
    "deleteConfirmation": "Are you sure you want to delete this student?",
    "deleteMultiple": "Are you sure you want to delete {count} students?",
    "deleteSuccess": "Student deleted successfully",
    "btn": {
      "multiAdd": "Adds",
      "singleAdd": "Add",
      "ExcelImport": "Import from Excel",
      "deleteStu": "Delete"
    },
    "DialogInsert": {
      "title": "Please enter student information"
    }
  },
  "Exam": {
    "title": "Exams",
    "createExam": "Create Exam",
    "editExam": "Edit Exam",
    "examName": "Exam Name",
    "examDate": "Exam Date",
    "noExams": "No exams found. Please create a new exam.",
    "viewDetails": "View Details"
  },
  "MonthlyExam": {
    "viewRanking": "Montly ranking",
    "viewAll": "View all",
    "monthlyScores": "Monthly scores",
    "enterAverage": "Enter average"
  },
  "SemesterExam": {
    "viewRanking": "Semester ranking",
    "semesterScores": "Semester scores",
    "semesterlyAverageRanking": "Semesterly average"
  },
  "MenuList": {
    "home": "Home",
    "classroom": "Classroom",
    "student": "Student",
    "exam": "Examing",
    "monthlyExam": "Monthly Exam",
    "SemesterExam": "Semester Exam",
    "setting": "Setting",
    "about": "About",
    "feedback": "Feedback",
    "manageSubject": "Manage Subject"
  }
};
export default messages;